export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_FETCH_ALL = 'USER_FETCH_ALL';
export const TRANSACTION_CREATE = 'TRANSACTION_CREATE';
export const TRANSACTION_FETCH_ALL = 'TRANSACTION_FETCH_ALL';
